# Site settings
name: David Martinez Jaramillo
title: David | Creator
description: Just human
url: https://martijaram.github.io/
baseurl: ''
email: davidmartijara@gmail.com
cover: https://martijaram.github.io/img/og.png
logo: https://martijaram.github.io/img/emojis/technologist.png

social:
  - title: email
    url: mailto:davidmartijara@gmail.com
  - title: twitter
    url: https://twitter.com/martijaram
  - title: LeetCode
    url: https://leetcode.com/martijaram
  - title: github
    url: https://github.com/martijaram


# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
