# Site settings
name: David Martinez Jaramillo
title: David | Creator
description: Creator who wants to build a stronger democracy with code
url: https://martijaram.github.io/
baseurl: ''
email: davidmartijara@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:davidmartijara@gmail.com
  - title: instagram
    url: https://instagram.com/martijaram
  - title: Medium
    url: http://medium.com/@martijaram
  - title: github
    url: https://github.com/martijaram

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
